pool:
  name: Hosted VS2017
  demands:
  - MSBuild
  - Xamarin.Android
  - msbuild
  - vstest
  - java

variables:
  BuildConfiguration: 'Release'
  Parameters.restorePkgSolution: '**\*.sln'
  Parameters.appFiles: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.restorePkgSolution)'

- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android project'
  inputs:
    projectFile: '**/*Droid*.csproj'
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'


- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'devops.perfectbody.keystore'
    apksignerKeystorePassword: '@Aa123456'
    apksignerKeystoreAlias: 'devops.perfectbody'
    apksignerKeyPassword: '@Aa123456'
    zipalign: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(build.binariesdirectory)/$(BuildConfiguration)'
    Contents: '*.apk'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'